#! /usr/bin/env python3

# Very very quick and dirty utility to take CSV files generated by LibreOffice or Excel and turn
# them into a JSON object that is readable by the GUI data stores. CSV file is expected in format:
# ID (string), boothNum (integer), vendorName (string), leftMapPixel, topMapPixel, width, height
#
# Example row:
# "276-0",276,"THE AMES COMPANY",2259,1503,74,183
#
# HOW TO RUN:
# $ ./csv2IVendorDirectoryMap.py path/to/csvfile.csv
#
# That output can then be added to public/show_vendors/(name_of_show).json
# and make sure to then add a new entry to public/show_vendors/all_shows.json matching the name.
#
# TIP for making the pixel coordinates:
# A good size of the image is using a width of 1600 pixels. Calibrated, this makes the fonts
# in the image more-or-less match that of the UI. See an example of this as a PNG file in
# public/show_vendors/2022-Fall-ACY.png to know how to crop any future images.

import csv
import json
import sys

vendors = {}

def parseCSVVendors(argv):
    with open(argv[1], newline='') as csvfile:
        csvVendors = csv.reader(csvfile, delimiter=',', quotechar='"')
        for row in csvVendors:
            vendors[row[0]] = {           # They boothId is the main 'key' to the map/object
                'boothNum': int(row[1]),  # boothNum is the actual booth # in the directory
                'vendor': row[2],         # the unique name of the vendor
                'x1': int(row[3]),        # leftmost pixel position of the booth on the map
                'y1': int(row[4]),        # topmost pixel position of the booth on the map
                'width': int(row[5]),     # width of the booth in pixels
                'height': int(row[6]),    # height of the booth in pixels
            }

        print(json.dumps(vendors))

if __name__ == "__main__":
    parseCSVVendors(sys.argv)
